networks:
  cpj_network:

volumes:
  cpj_volume:

services:
  mysql:
    image: mysql:8.4.3
    container_name: cpj_mysql_container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cric_pages_jaunes
      MYSQL_USER: cpj
      MYSQL_PASSWORD: cpj
    healthcheck:
      test: [ "CMD", "mysql", "--version" ]
      interval: 5s
      retries: 5
      timeout: 5s
    volumes:
        - cpj_volume:/var/lib/mysql
    networks:
      - cpj_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpj_php_fpm_container
    expose:
      - 9000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "php", "--version" ]
      interval: 3s
      retries: 5
      timeout: 5s
    volumes:
      - ./:/var/www/html
    networks:
      - cpj_network

  composer:
    image: composer:2.8.4
    container_name: cpj_composer_container
    working_dir: /var/www/html
    command: composer install
    volumes:
      - ./:/var/www/html
    networks:
      - cpj_network

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpj_artisan_container
    working_dir: /var/www/html
    command: sh -c "php artisan key:generate && php artisan migrate"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
    networks:
      - cpj_network

  nginx:
    image: nginx:stable-alpine
    container_name: cpj_nginx_container
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      php-fpm:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cpj_network
